### ISSUE TITLE
Indexer for mainnet/goerli

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#131]
We need to explore different options.
I don't know which one will be the way to go, although most likely we want to provide support for multiple in the long-run (and allow users to choose which one they want to use based on what API key they have for themselves)

What we need:
- easy querying of the transaction history for any given address
- querying of current ERC20 / ERC721 balances

For now I'm considering:
- etherscan API
- n.xyz
- https://www.tryshadow.xyz/

@gabrielpoca maybe you know more options?

TODO: 
- [x] track ETH balance
- [x] track ERC20 tokens
- [x] track ERC721 tokens
- [ ] track transaction history

Pull Requests:
- #258 
- #261 
- #260 
- #259 
- #262

**Comment by naps62** [comment]
We're integrating alchemy.com now in #202
