### ISSUE TITLE
Networks

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#18]
Instead of a single RPC URL on settings, we want something akin to what metamask has:
- A dropdown where we can quickly switch between different networks
- A pre-existing list of default networks
- Ability to add new custom networks

---

- [x] #17
- [x] new store fields for storing custom networks
- [x] new settings page to configure networks
- [x] replace settings' RPC URL field in favor of a network selector
